spring:
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

logging:
  level:
    root: WARN
    com.recipes: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info